# Generated by Django 6.0.2 on 2026-02-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trackedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='stripe_subscription_item_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
